### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by charfweh** [ARealWant/Guildbomb#3]
This is actually so stupid, arent those the function of the official discord library itself? my man really had the audacity to "code" an "exploit" to "bomb" the server which uses the library function itself, this will work only in the server the bot is in, mind you every mainstream bot has this ability to do it, and your whole code will fail to deliver just when you remove out the damn admin role. Please give me a break, I'm tired of repo like these.

**Comment by ARealWant** [comment]
Hello,

I would appreciate it, if you don't abuse the **Issues** tab for letting people know your opinion. You are on GitHub, what do you expect? Don't tell me that you thought, all developers would code just for you, to satiate you? I did this piece of code in like 20 minutes, just to show people, how **easy it can be** to raid servers. My intention's to let people know, that they shouldn't invite every bot to their server and wonder why they get raided.

Do me a favor next time, read the ReadMe and stop complaining about things, in a freaking
platform which has million of codes people do, because they are bored or just want to do something.

I'll close this comment due to you're not able to read the readme.md and complaining about things with arguments
that don't make any sense, on an open-source platform, **where definetly not everything will agree with your opinion**.

Have a great day
ARealWant
